/*
 * generated by Xtext 2.16.0
 */
package hu.bme.aut.apitransform.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractApiTransformScopeProvider extends DelegatingScopeProvider {
}
