/**
 * generated by Xtext 2.16.0
 */
package hu.bme.aut.apitransform.validation;

import hu.bme.aut.apitransform.validation.AbstractApiTransformValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ApiTransformValidator extends AbstractApiTransformValidator {
}
