/**
 * generated by Xtext 2.16.0
 */
package hu.bme.aut.apitransform.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import hu.bme.aut.apitransform.ApiTransformRuntimeModule;
import hu.bme.aut.apitransform.ApiTransformStandaloneSetup;
import hu.bme.aut.apitransform.ide.ApiTransformIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class ApiTransformIdeSetup extends ApiTransformStandaloneSetup {
  @Override
  public Injector createInjector() {
    ApiTransformRuntimeModule _apiTransformRuntimeModule = new ApiTransformRuntimeModule();
    ApiTransformIdeModule _apiTransformIdeModule = new ApiTransformIdeModule();
    return Guice.createInjector(Modules2.mixin(_apiTransformRuntimeModule, _apiTransformIdeModule));
  }
}
