/**
 * generated by Xtext 2.16.0
 */
package hu.bme.aut.apitransform.ide;

import hu.bme.aut.apitransform.ide.AbstractApiTransformIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ApiTransformIdeModule extends AbstractApiTransformIdeModule {
}
