/*
 * generated by Xtext 2.16.0
 */
package hu.bme.aut.apitransform.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class ApiTransformProposalProvider extends AbstractApiTransformProposalProvider {
}
