/**
 * generated by Xtext 2.16.0
 */
package hu.bme.aut.apitransform.apiTransform;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function Prefix</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.aut.apitransform.apiTransform.FunctionPrefix#getPrefixes <em>Prefixes</em>}</li>
 * </ul>
 *
 * @see hu.bme.aut.apitransform.apiTransform.ApiTransformPackage#getFunctionPrefix()
 * @model
 * @generated
 */
public interface FunctionPrefix extends EObject
{
  /**
   * Returns the value of the '<em><b>Prefixes</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Prefixes</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prefixes</em>' attribute list.
   * @see hu.bme.aut.apitransform.apiTransform.ApiTransformPackage#getFunctionPrefix_Prefixes()
   * @model unique="false"
   * @generated
   */
  EList<String> getPrefixes();

} // FunctionPrefix
