/**
 * generated by Xtext 2.16.0
 */
package hu.bme.aut.apitransform.apiTransform;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Target</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.aut.apitransform.apiTransform.Target#isStatic <em>Static</em>}</li>
 *   <li>{@link hu.bme.aut.apitransform.apiTransform.Target#getPrefix <em>Prefix</em>}</li>
 *   <li>{@link hu.bme.aut.apitransform.apiTransform.Target#getFunction <em>Function</em>}</li>
 * </ul>
 *
 * @see hu.bme.aut.apitransform.apiTransform.ApiTransformPackage#getTarget()
 * @model
 * @generated
 */
public interface Target extends EObject
{
  /**
   * Returns the value of the '<em><b>Static</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Static</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Static</em>' attribute.
   * @see #setStatic(boolean)
   * @see hu.bme.aut.apitransform.apiTransform.ApiTransformPackage#getTarget_Static()
   * @model
   * @generated
   */
  boolean isStatic();

  /**
   * Sets the value of the '{@link hu.bme.aut.apitransform.apiTransform.Target#isStatic <em>Static</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Static</em>' attribute.
   * @see #isStatic()
   * @generated
   */
  void setStatic(boolean value);

  /**
   * Returns the value of the '<em><b>Prefix</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Prefix</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prefix</em>' containment reference.
   * @see #setPrefix(FunctionPrefix)
   * @see hu.bme.aut.apitransform.apiTransform.ApiTransformPackage#getTarget_Prefix()
   * @model containment="true"
   * @generated
   */
  FunctionPrefix getPrefix();

  /**
   * Sets the value of the '{@link hu.bme.aut.apitransform.apiTransform.Target#getPrefix <em>Prefix</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prefix</em>' containment reference.
   * @see #getPrefix()
   * @generated
   */
  void setPrefix(FunctionPrefix value);

  /**
   * Returns the value of the '<em><b>Function</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Function</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function</em>' containment reference.
   * @see #setFunction(Function)
   * @see hu.bme.aut.apitransform.apiTransform.ApiTransformPackage#getTarget_Function()
   * @model containment="true"
   * @generated
   */
  Function getFunction();

  /**
   * Sets the value of the '{@link hu.bme.aut.apitransform.apiTransform.Target#getFunction <em>Function</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function</em>' containment reference.
   * @see #getFunction()
   * @generated
   */
  void setFunction(Function value);

} // Target
