/**
 * generated by Xtext 2.16.0
 */
package hu.bme.aut.apitransform.apiTransform;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Transformation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.aut.apitransform.apiTransform.Transformation#getSource <em>Source</em>}</li>
 *   <li>{@link hu.bme.aut.apitransform.apiTransform.Transformation#getTarget <em>Target</em>}</li>
 * </ul>
 *
 * @see hu.bme.aut.apitransform.apiTransform.ApiTransformPackage#getTransformation()
 * @model
 * @generated
 */
public interface Transformation extends EObject
{
  /**
   * Returns the value of the '<em><b>Source</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Source</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' containment reference.
   * @see #setSource(Function)
   * @see hu.bme.aut.apitransform.apiTransform.ApiTransformPackage#getTransformation_Source()
   * @model containment="true"
   * @generated
   */
  Function getSource();

  /**
   * Sets the value of the '{@link hu.bme.aut.apitransform.apiTransform.Transformation#getSource <em>Source</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source</em>' containment reference.
   * @see #getSource()
   * @generated
   */
  void setSource(Function value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Target</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' containment reference.
   * @see #setTarget(Target)
   * @see hu.bme.aut.apitransform.apiTransform.ApiTransformPackage#getTransformation_Target()
   * @model containment="true"
   * @generated
   */
  Target getTarget();

  /**
   * Sets the value of the '{@link hu.bme.aut.apitransform.apiTransform.Transformation#getTarget <em>Target</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' containment reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(Target value);

} // Transformation
