/**
 * generated by Xtext 2.16.0
 */
package hu.bme.aut.apitransform.ui;

import hu.bme.aut.apitransform.ui.AbstractApiTransformUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ApiTransformUiModule extends AbstractApiTransformUiModule {
  public ApiTransformUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
