/**
 * generated by Xtext 2.16.0
 */
package hu.bme.aut.apitransform;

import hu.bme.aut.apitransform.ApiTransformStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ApiTransformStandaloneSetup extends ApiTransformStandaloneSetupGenerated {
  public static void doSetup() {
    new ApiTransformStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
