/**
 * generated by Xtext 2.16.0
 */
package hu.bme.aut.apitransform;

import hu.bme.aut.apitransform.AbstractApiTransformRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ApiTransformRuntimeModule extends AbstractApiTransformRuntimeModule {
}
