/*
 * generated by Xtext 2.16.0
 */
package hu.bme.aut.apitransform.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractApiTransformValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(hu.bme.aut.apitransform.apiTransform.ApiTransformPackage.eINSTANCE);
		return result;
	}
}
