/*
 * generated by Xtext 2.16.0
 */
package hu.bme.aut.apitransform.parser.antlr;

import com.google.inject.Inject;
import hu.bme.aut.apitransform.parser.antlr.internal.InternalApiTransformParser;
import hu.bme.aut.apitransform.services.ApiTransformGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ApiTransformParser extends AbstractAntlrParser {

	@Inject
	private ApiTransformGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalApiTransformParser createParser(XtextTokenStream stream) {
		return new InternalApiTransformParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public ApiTransformGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ApiTransformGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
