/*
 * generated by Xtext 2.16.0
 */
package hu.bme.aut.apitransform.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ApiTransformAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("hu/bme/aut/apitransform/parser/antlr/internal/InternalApiTransform.tokens");
	}
}
