/*
 * generated by Xtext 2.16.0
 */
package hu.bme.aut.apitransform.ui;

import com.google.inject.Injector;
import hu.bme.aut.apitransform.ui.internal.ApitransformActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ApiTransformExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(ApitransformActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		ApitransformActivator activator = ApitransformActivator.getInstance();
		return activator != null ? activator.getInjector(ApitransformActivator.HU_BME_AUT_APITRANSFORM_APITRANSFORM) : null;
	}

}
