/**
 * generated by Xtext 2.16.0
 */
package hu.bme.aut.apitransform.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class ApiTransformQuickfixProvider extends DefaultQuickfixProvider {
}
