/**
 * generated by Xtext 2.16.0
 */
package hu.bme.aut.apitransform.scoping;

import hu.bme.aut.apitransform.scoping.AbstractApiTransformScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class ApiTransformScopeProvider extends AbstractApiTransformScopeProvider {
}
