/*
 * generated by Xtext 2.16.0
 */
package hu.bme.aut.apitransform.ui.tests;

import com.google.inject.Injector;
import hu.bme.aut.apitransform.ui.internal.ApitransformActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class ApiTransformUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ApitransformActivator.getInstance().getInjector("hu.bme.aut.apitransform.ApiTransform");
	}

}
