/*
 * generated by Xtext 2.16.0
 */
package hu.bme.aut.apitransform


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ApiTransformRuntimeModule extends AbstractApiTransformRuntimeModule {
}
