/*
 * generated by Xtext 2.16.0
 */
package hu.bme.aut.apitransform


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ApiTransformStandaloneSetup extends ApiTransformStandaloneSetupGenerated {

	def static void doSetup() {
		new ApiTransformStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
